Do update of achievements in background
tom0334/HuisET pull request #298
Opened 2021-05-15 23:10 UTC by tom0334

2021-05-16 00:44 UTC, BovdBerg requested changes

2021-05-16 00:44 UTC, BovdBerg commented on app/src/main/java/com/tobo/huiset/achievements/Achievements.kt
> +/*    fun checkAgainForPerson(person: Person): List<AchievementCompletion> {
Just remove these lines, don't leave outcommented code

2021-05-16 00:44 UTC, BovdBerg commented on app/src/main/java/com/tobo/huiset/extendables/CelebratingHuisEtActivity.kt
> +                "${changed.size} achievments unlocked!",
typo in Toast

2021-05-20 14:33 UTC, tom0334 commented on app/src/main/java/com/tobo/huiset/achievements/Achievements.kt
> +/*    fun checkAgainForPerson(person: Person): List<AchievementCompletion> {
Done

2021-05-20 15:09 UTC, BovdBerg approved these changes

2021-05-20 15:10 UTC, merged